### ISSUE TITLE
Profiles > Card > SLP Card: Icon and layout style issues

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#307]
TM says, “the icons look a bit crunched up against the text on my ipad.
<img width="284" alt="screen shot 2018-12-06 at 7 02 45 pm" src="https://user-images.githubusercontent.com/8650944/49619394-6b8ce900-f98a-11e8-92d9-e3f9d84987e9.png">

**Comment by helencarey** [comment]
This should resolve the issue. 
At some point, we should consider making our own icons, and not relying on the ionicon defaults.

**issue:**
Either ionic or cordova injects icons appropriate to the platform when you build. If you use these icons outside of ion elements, the icons sometimes elude our custom styling. 

**fix:**
To get better control over what will show up:
- go to lib/ionic/fonts/ionicons and find the name of the platform-specific version of the icon, use this to class your `<i>`
-  size and position the `<i>` with css, don't just rely on the framework. My custom class is called, '.r-ico'   


**vQA**
The icons in the Profiles drawer and card should look like the pic below.
(if they do not, @erinmdoty lmk)
![simulator screen shot - ipad air 2 - 2018-12-10 at 17 24 08](https://user-images.githubusercontent.com/8650944/49765421-73a59b00-fca0-11e8-994a-845a3085f9d8.png)

**Comment by erinmdoty** [comment]
@helencarey In v1.0.31 it looks the same (crunched up a bit) as in the original comment. I'll test in v1.0.32 and let you know if not resolved.

**Comment by helencarey** [comment]
> @helencarey In v1.0.31 it looks the same (crunched up a bit) as in the original comment. I'll test in v1.0.32 and let you know if not resolved.

oh right. @erinmdoty, I've been moving the stuff that I've finished to the Test list, but none of the fixes will show up in your app until v1.0.32 is out -- so no need to test my stuff yet.
